routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

// Admin routes
Route::group(['middleware' => 'auth'], function () {

  // Route::post('mark-notification-read', ['uses' => 'NotificationController@markAllRead'])->name('mark-notification-read');

  // Admin routes
  Route::group(
    ['namespace' => 'Admin', 'prefix' => 'account', 'as' => 'admin.'],
    function () {

      Route::post('business-services/store-images', 'BusinessServiceController@storeImages')->name('business-services.storeImages');
      Route::post('business-services/update-images', 'BusinessServiceController@updateImages')->name('business-services.updateImages');

      Route::get('coupons/data', 'CouponController@data')->name('coupons.data');

      Route::post('todo-items/update-todo-item', 'TodoItemController@updateTodoItem')->name('todo-items.updateTodoItem');

      Route::post('save-booking-times-field', 'SettingController@saveBookingTimesField')->name('save-booking-times-field');

      Route::resources(
        [
          'locations' => 'LocationController',
          'categories' => 'CategoryController',
          'business-services' => 'BusinessServiceController',
          'pages' => 'PageController',
          'settings' => 'SettingController',
          'booking-times' => 'BookingTimeController',
          'tax-settings' => 'TaxSettingController',
          'currency-settings' => 'CurrencySettingController',
          'language-settings' => 'LanguageSettingController',
          'email-settings' => 'SmtpSettingController',
          'theme-settings' => 'ThemeSettingController',
          'front-theme-settings' => 'FrontThemeSettingController',
          'customers' => 'CustomerController',
          'credential' => 'PaymentCredentialSettingController',
          'sms-settings' => 'SmsSettingController',
          'coupons' => 'CouponController',
          'sms-settings' => 'SmsSettingController',
          'todo-items' => 'TodoItemController',
          'deals' => 'DealController',
        ]
      );


      Route::post('selectLocation', 'DealController@selectLocation')->name('deals.selectLocation');
      Route::post('selectServices', 'DealController@selectServices')->name('deals.selectServices');
      Route::get('resetSelection', 'DealController@resetSelection')->name('deals.resetSelection');
      Route::post('makeDealWithMultipleLocation', 'DealController@makeDealWithMultipleLocation')->name('deals.makeDealWithMultipleLocation');
      Route::post('makeDeal', 'DealController@makeDeal')->name('deals.makeDeal');
      Route::post('makeDealMultipleLocation', 'DealController@makeDealMultipleLocation')->name('deals.makeDealMultipleLocation');


      Route::post('change-language/{code}', 'SettingController@changeLanguage')->name('changeLanguage');

      Route::post('change-language/{code}', 'SettingController@changeLanguage')->name('changeLanguage');
      Route::post('role-permission/add-role', 'RolePermissionSettingController@addRole')->name('role-permission.addRole');
      Route::post('role-permission/add-members/{role_id}', 'RolePermissionSettingController@addMembers')->name('role-permission.addMembers');
      Route::get('role-permission/get-members/{role_id}', 'RolePermissionSettingController@getMembers')->name('role-permission.getMembers');
      Route::get('role-permission/get-members-to-add/{id}', 'RolePermissionSettingController@getMembersToAdd')->name('role-permission.getMembersToAdd');
      Route::delete('role-permission/remove-member', 'RolePermissionSettingController@removeMember')->name('role-permission.removeMember');
      Route::get('role-permission/data', 'RolePermissionSettingController@data')->name('role-permission.data');
      Route::post('role-permission/toggleAllPermissions', 'RolePermissionSettingController@toggleAllPermissions')->name('role-permission.toggleAllPermissions');
      Route::resource('role-permission', 'RolePermissionSettingController');

      Route::put('change-language-status/{id}', 'LanguageSettingController@changeStatus')->name('language-settings.changeStatus');
      Route::get('smtp-settings/sent-test-email', ['uses' => 'SmtpSettingController@sendTestEmail'])->name('email-settings.sendTestEmail');
      Route::get('reports/earningTable', ['uses' => 'ReportController@earningTable'])->name('reports.earningTable');
      Route::post('reports/earningChart', ['uses' => 'ReportController@earningReportChart'])->name('reports.earningReportChart');
      Route::get('reports', ['uses' => 'ReportController@index'])->name('reports.index');

      Route::get('reports/salesTable', ['uses' => 'ReportController@salesTable'])->name('reports.salesTable');
      Route::get('reports/tabularTable', ['uses' => 'ReportController@tabularTable'])->name('reports.tabularTable');
      Route::post('reports/salesChart', ['uses' => 'ReportController@salesReportChart'])->name('reports.salesReportChart');

      /* Graphical reporting section  */
      Route::get('reports/userTypeChart', ['uses' => 'ReportController@userTypeChart'])->name('reports.userTypeChart');
      Route::get('reports/serviceTypeChart', ['uses' => 'ReportController@serviceTypeChart'])->name('reports.serviceTypeChart');
      Route::get('reports/bookingSourceChart', ['uses' => 'ReportController@bookingSourceChart'])->name('reports.bookingSourceChart');
      Route::post('reports/bookingPerDayChart', ['uses' => 'ReportController@bookingPerDayChart'])->name('reports.bookingPerDayChart');
      Route::post('reports/paymentPerDayChart', ['uses' => 'ReportController@paymentPerDayChart'])->name('reports.paymentPerDayChart');
      Route::post('reports/bookingPerMonthChart', ['uses' => 'ReportController@bookingPerMonthChart'])->name('reports.bookingPerMonthChart');
      Route::post('reports/paymentPerMonthChart', ['uses' => 'ReportController@paymentPerMonthChart'])->name('reports.paymentPerMonthChart');
      Route::post('reports/bookingPerYearChart', ['uses' => 'ReportController@bookingPerYearChart'])->name('reports.bookingPerYearChart');
      Route::post('reports/bookingPerYearChart', ['uses' => 'ReportController@bookingPerYearChart'])->name('reports.bookingPerYearChart');
      Route::post('reports/paymentPerYearChart', ['uses' => 'ReportController@paymentPerYearChart'])->name('reports.paymentPerYearChart');

      Route::get('reports/customer', ['uses' => 'ReportController@customer'])->name('reports.customer');
      Route::get('pos/select-customer', ['uses' => 'POSController@selectCustomer'])->name('pos.select-customer');
      Route::get('pos/search-customer', ['uses' => 'POSController@searchCustomer'])->name('pos.search-customer');
      Route::get('pos/filter-services', ['uses' => 'POSController@filterServices'])->name('pos.filter-services');
      Route::get('pos/addCart', ['uses' => 'POSController@addCart'])->name('pos.addCart');
      Route::post('pos/apply-coupon', ['uses' => 'POSController@applyCoupon'])->name('pos.apply-coupon');
      Route::post('pos/update-coupon', ['uses' => 'POSController@updateCoupon'])->name('pos.update-coupon');
      Route::resource('pos', 'POSController');

      Route::post('employee/changeRole', 'EmployeeController@changeRole')->name('employee.changeRole');
      Route::resource('employee', 'EmployeeController');
      Route::resource('employee-group', 'EmployeeGroupController');

      Route::resource('update-application', 'UpdateApplicationController');
      Route::resource('search', 'SearchController');

      Route::get('dashboard', 'ShowDashboard')->name('dashboard');

      Route::post('bookings/update-coupon', ['uses' => 'BookingController@updateCoupon'])->name('bookings.update-coupon');
      Route::post('multiStatusUpdate', ['uses' => 'BookingController@multiStatusUpdate'])->name('bookings.multiStatusUpdate');
      Route::post('sendReminder', ['uses' => 'BookingController@sendReminder'])->name('bookings.sendReminder');
      Route::post('bookings/{status?}', ['uses' => 'BookingController@index'])->name('bookings.index');
      Route::post('bookings/requestCancel/{id}', ['uses' => 'BookingController@requestCancel'])->name('bookings.requestCancel');
      Route::get('bookings/download/{id}', ['uses' => 'BookingController@download'])->name('bookings.download');
      Route::resources([
        'bookings' => 'BookingController',
        'profile' => 'ProfileController'
      ]);
    }
  );

  Route::get('change-mobile', 'VerifyMobileController@changeMobile')->name('changeMobile');
  Route::post('/send-otp-code', 'VerifyMobileController@sendVerificationCode')->name('sendOtpCode');
  Route::post('/send-otp-code/account', 'VerifyMobileController@sendVerificationCode')->name('sendOtpCode.account');
  Route::post('/verify-otp-phone', 'VerifyMobileController@verifyOtpCode')->name('verifyOtpCode');
  Route::post('/verify-otp-phone/account', 'VerifyMobileController@verifyOtpCode')->name('verifyOtpCode.account');
  Route::get('/remove-session', 'VerifyMobileController@removeSession')->name('removeSession');
});

Route::group(
  ['namespace' => 'Front', 'as' => 'front.'],
  function () {
    Route::get('/', ['uses' => 'FrontController@index'])->name('index');
    Route::resource('rooms', 'RoomsController');
    Route::resource('booker', 'BookerController');

    Route::group(['middleware' => 'cookieRedirect'], function () {
      Route::get('/booking', ['uses' => 'FrontController@bookingPage'])->name('bookingPage');
      Route::get('/checkout', ['uses' => 'FrontController@checkoutPage'])->name('checkoutPage');
    });
    Route::get('/cart', ['uses' => 'FrontController@cartPage'])->name('cartPage');

resources/views/admin/page/create.blade.php
<div class="modal-header">
    <h4 class="modal-title">@lang('app.createNew') @lang('app.page')</h4>
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
</div>
<div class="modal-body">
    <form role="form" id="createForm" class="ajax-form" method="POST">
        @csrf
        <div class="row">
            <div class="col-md">
                <!-- text input -->
                <div class="form-group">
                    <label>@lang('app.page') @lang('app.title')</label>
                    <input type="text" name="title" id="title" class="form-control form-control-lg" value="">
                </div>
            </div>
            <div class="col-md">
                <div class="form-group">
                    <label>@lang('app.page') @lang('app.slug')</label>
                    <input type="text" name="slug" id="slug" class="form-control form-control-lg" value="">
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label>@lang('app.page') @lang('app.content')</label>
                    <textarea name="content" id="content" cols="30" class="form-control-lg form-control"
                        rows="4"></textarea>
                </div>
            </div>
        </div>
        <div class="form-group">
            <button type="button" id="save-form" class="btn btn-success btn-light-round"><i
                    class="fa fa-check"></i> @lang('app.save')</button>
        </div>
    </form>
</div>

<script>
    $(function () {
        $('#content').summernote({
            dialogsInBody: true,
            height: 300,
            toolbar: [
            // [groupName, [list of button]]
            ['style', ['bold', 'italic', 'underline', 'clear']],
            ['font', ['strikethrough']],
            ['fontsize', ['fontsize']],
            ['para', ['ul', 'ol', 'paragraph']],
            ["view", ["fullscreen"]]
        ]
        })
    })
    $('#save-form').click(function () {
        // CKEDITOR.instances.content.updateElement()
        const form = $('#createForm');

        $.easyAjax({
            url: '{{route('admin.pages.store')}}',
            container: '#createForm',
            type: "POST",
            redirect: true,
            data: form.serialize(),
            success: function (response) {
                if(response.status == 'success'){
                    $('#application-lg-modal').modal('hide');
                    table._fnDraw();
                }
            }
        })
    });

    function createSlug(value) {
        value = value.replace(/\s\s+/g, ' ');
        let slug = value.split(' ').join('-').toLowerCase();
        slug = slug.replace(/--+/g, '-');
        $('#slug').val(slug);
    }

    $('#title').keyup(function (e) {
        createSlug($(this).val());
    });

    $('#slug').keyup(function (e) {
        createSlug($(this).val());
    });
</script>

resources/views/admin/page/edit.blade.php
@extends('layouts.master')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card card-dark">
                <div class="card-header">
                    <h3 class="modal-title">@lang('app.edit') @lang('app.page')</h3>
                </div>
                <div class="card-body">
                    <form role="form" id="editForm"  class="ajax-form" method="POST">
                        @csrf
                        @method('PUT')
                        <input type="hidden" name="id" value="{{ $page->id }}">
                        <div class="row">
                            <div class="col-md">
                                <!-- text input -->
                                <div class="form-group">
                                    <label>@lang('app.page') @lang('app.title')</label>
                                    <input type="text" name="title" id="title" class="form-control form-control-lg" value="{{ $page->title }}" autofocus>
                                </div>
                            </div>
                            <div class="col-md">
                                <div class="form-group">
                                    <label>@lang('app.page') @lang('app.slug')</label>
                                    <input type="text" name="slug" id="slug" class="form-control form-control-lg" value="{{ $page->slug }}">
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>@lang('app.page') @lang('app.content')</label>
                                    <textarea name="content" id="content" cols="30" class="form-control-lg form-control" rows="4">{{ $page->content }}</textarea>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <button type="button" id="save-form" class="btn btn-success btn-light-round"><i
                                        class="fa fa-check"></i> @lang('app.save')</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('footer-js')
    <script>
        $(function() {
            $('#content').summernote({
                // dialogsInBody: true,
                height: 300,
                toolbar: [
                // [groupName, [list of button]]
                ['style', ['bold', 'italic', 'underline', 'clear']],
                ['font', ['strikethrough']],
                ['fontsize', ['fontsize']],
                ['para', ['ul', 'ol', 'paragraph']],
                ["view", ["fullscreen"]]
            ]
            })
        })
        $('#save-form').click(function () {
            const form = $('#editForm');

            $.easyAjax({
                url: '{{route('admin.pages.update', $page->slug)}}',
                container: '#editForm',
                type: "PUT",
                redirect: true,
                data: form.serialize(),
                success: function (response) {
                    if(response.status == 'success'){
                        // location.href = '{{ route('admin.search.show', session()->get("searchKey")) }}'
                        location.href = '{{ route('admin.settings.index').'#front-pages' }}'
                    }
                }
            })
        });

        function createSlug(value) {
            value = value.replace(/\s\s+/g, ' ');
            let slug = value.split(' ').join('-').toLowerCase();
            slug = slug.replace(/--+/g, '-');
            $('#slug').val(slug);
        }

        $('#title').keyup(function(e) {
            createSlug($(this).val());
        });

        $('#slug').keyup(function(e) {
            createSlug($(this).val());
        });
    </script>
@endpush

resources/views/admin/page/edit_modal.blade.php
<div class="modal-header">
    <h4 class="modal-title">@lang('app.edit') @lang('app.page')</h4>
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
</div>
<div class="modal-body">
    <form role="form" id="editForm"  class="ajax-form" method="POST">
        @csrf
        @method('PUT')
        <input type="hidden" name="id" value="{{ $page->id }}">
        <div class="row">
            <div class="col-md">
                <!-- text input -->
                <div class="form-group">
                    <label>@lang('app.page') @lang('app.title')</label>
                    <input type="text" name="title" id="title" class="form-control form-control-lg" value="{{ $page->title }}" autofocus>
                </div>
            </div>
            <div class="col-md">
                <div class="form-group">
                    <label>@lang('app.page') @lang('app.slug')</label>
                    <input type="text" name="slug" id="slug" class="form-control form-control-lg" value="{{ $page->slug }}">
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label>@lang('app.page') @lang('app.content')</label>
                    <textarea name="content" id="content" cols="30" class="form-control-lg form-control" rows="4">{{ $page->content }}</textarea>
                </div>
            </div>
        </div>
        <div class="form-group">
            <button type="button" id="save-form" class="btn btn-success btn-light-round"><i
                        class="fa fa-check"></i> @lang('app.save')</button>
        </div>
    </form>
</div>

<script>
    $(function() {
        $('#content').summernote({
            dialogsInBody: true,
            height: 300,
            toolbar: [
            // [groupName, [list of button]]
            ['style', ['bold', 'italic', 'underline', 'clear']],
            ['font', ['strikethrough']],
            ['fontsize', ['fontsize']],
            ['para', ['ul', 'ol', 'paragraph']],
            ["view", ["fullscreen"]]
        ]
        })
    })
    $('#save-form').click(function () {
        const form = $('#editForm');

        $.easyAjax({
            url: '{{route('admin.pages.update', $page->slug)}}',
            container: '#editForm',
            type: "PUT",
            redirect: true,
            data: form.serialize(),
            success: function (response) {
                if(response.status == 'success'){
                    $('#application-lg-modal').modal('hide');
                    table._fnDraw();
                }
            }
        })
    });

    function createSlug(value) {
        value = value.replace(/\s\s+/g, ' ');
        let slug = value.split(' ').join('-').toLowerCase();
        slug = slug.replace(/--+/g, '-');
        $('#slug').val(slug);
    }

    $('#title').keyup(function(e) {
        createSlug($(this).val());
    });

    $('#slug').keyup(function(e) {
        createSlug($(this).val());
    });
</script>

resources/views/admin/page/index.blade.php
<div class="table-responsive">
    <div class="d-flex justify-content-center justify-content-md-end mb-3">
        <a href="javascript:;" id="create-page" class="btn btn-rounded btn-primary mb-1"><i class="fa fa-plus"></i> @lang('app.createNew')</a>
    </div>

    <table id="myTable" class="table w-100">
        <thead>
            <tr>
                <th>#</th>
                <th>@lang('app.title')</th>
                <th>@lang('app.slug')</th>
                <th>@lang('app.action')</th>
            </tr>
        </thead>
    </table>

</div>