routes/web.php
      Route::get('role-permission/get-members/{role_id}', 'RolePermissionSettingController@getMembers')->name('role-permission.getMembers');
      Route::get('role-permission/get-members-to-add/{id}', 'RolePermissionSettingController@getMembersToAdd')->name('role-permission.getMembersToAdd');
      Route::delete('role-permission/remove-member', 'RolePermissionSettingController@removeMember')->name('role-permission.removeMember');
      Route::get('role-permission/data', 'RolePermissionSettingController@data')->name('role-permission.data');
      Route::post('role-permission/toggleAllPermissions', 'RolePermissionSettingController@toggleAllPermissions')->name('role-permission.toggleAllPermissions');
      Route::resource('role-permission', 'RolePermissionSettingController');

      Route::put('change-language-status/{id}', 'LanguageSettingController@changeStatus')->name('language-settings.changeStatus');
      Route::get('smtp-settings/sent-test-email', ['uses' => 'SmtpSettingController@sendTestEmail'])->name('email-settings.sendTestEmail');
      Route::get('reports/earningTable', ['uses' => 'ReportController@earningTable'])->name('reports.earningTable');
      Route::post('reports/earningChart', ['uses' => 'ReportController@earningReportChart'])->name('reports.earningReportChart');
      Route::get('reports', ['uses' => 'ReportController@index'])->name('reports.index');

      Route::get('reports/salesTable', ['uses' => 'ReportController@salesTable'])->name('reports.salesTable');
      Route::get('reports/tabularTable', ['uses' => 'ReportController@tabularTable'])->name('reports.tabularTable');
      Route::post('reports/salesChart', ['uses' => 'ReportController@salesReportChart'])->name('reports.salesReportChart');

      /* Graphical reporting section  */
      Route::get('reports/userTypeChart', ['uses' => 'ReportController@userTypeChart'])->name('reports.userTypeChart');
      Route::get('reports/serviceTypeChart', ['uses' => 'ReportController@serviceTypeChart'])->name('reports.serviceTypeChart');
      Route::get('reports/bookingSourceChart', ['uses' => 'ReportController@bookingSourceChart'])->name('reports.bookingSourceChart');
      Route::post('reports/bookingPerDayChart', ['uses' => 'ReportController@bookingPerDayChart'])->name('reports.bookingPerDayChart');
      Route::post('reports/paymentPerDayChart', ['uses' => 'ReportController@paymentPerDayChart'])->name('reports.paymentPerDayChart');
      Route::post('reports/bookingPerMonthChart', ['uses' => 'ReportController@bookingPerMonthChart'])->name('reports.bookingPerMonthChart');
      Route::post('reports/paymentPerMonthChart', ['uses' => 'ReportController@paymentPerMonthChart'])->name('reports.paymentPerMonthChart');
      Route::post('reports/bookingPerYearChart', ['uses' => 'ReportController@bookingPerYearChart'])->name('reports.bookingPerYearChart');
      Route::post('reports/bookingPerYearChart', ['uses' => 'ReportController@bookingPerYearChart'])->name('reports.bookingPerYearChart');
      Route::post('reports/paymentPerYearChart', ['uses' => 'ReportController@paymentPerYearChart'])->name('reports.paymentPerYearChart');

      Route::get('reports/customer', ['uses' => 'ReportController@customer'])->name('reports.customer');
      Route::get('pos/select-customer', ['uses' => 'POSController@selectCustomer'])->name('pos.select-customer');
      Route::get('pos/search-customer', ['uses' => 'POSController@searchCustomer'])->name('pos.search-customer');
      Route::get('pos/filter-services', ['uses' => 'POSController@filterServices'])->name('pos.filter-services');
      Route::get('pos/addCart', ['uses' => 'POSController@addCart'])->name('pos.addCart');
      Route::post('pos/apply-coupon', ['uses' => 'POSController@applyCoupon'])->name('pos.apply-coupon');
      Route::post('pos/update-coupon', ['uses' => 'POSController@updateCoupon'])->name('pos.update-coupon');
      Route::resource('pos', 'POSController');

      Route::post('employee/changeRole', 'EmployeeController@changeRole')->name('employee.changeRole');
      Route::resource('employee', 'EmployeeController');
      Route::resource('employee-group', 'EmployeeGroupController');

      Route::resource('update-application', 'UpdateApplicationController');
      Route::resource('search', 'SearchController');

      Route::get('dashboard', 'ShowDashboard')->name('dashboard');

      Route::post('bookings/update-coupon', ['uses' => 'BookingController@updateCoupon'])->name('bookings.update-coupon');
      Route::post('multiStatusUpdate', ['uses' => 'BookingController@multiStatusUpdate'])->name('bookings.multiStatusUpdate');
      Route::post('sendReminder', ['uses' => 'BookingController@sendReminder'])->name('bookings.sendReminder');
      Route::post('bookings/{status?}', ['uses' => 'BookingController@index'])->name('bookings.index');
      Route::post('bookings/requestCancel/{id}', ['uses' => 'BookingController@requestCancel'])->name('bookings.requestCancel');
      Route::get('bookings/download/{id}', ['uses' => 'BookingController@download'])->name('bookings.download');
      Route::resources([
        'bookings' => 'BookingController',
        'profile' => 'ProfileController'
      ]);
    }
  );

  Route::get('change-mobile', 'VerifyMobileController@changeMobile')->name('changeMobile');
  Route::post('/send-otp-code', 'VerifyMobileController@sendVerificationCode')->name('sendOtpCode');
  Route::post('/send-otp-code/account', 'VerifyMobileController@sendVerificationCode')->name('sendOtpCode.account');
  Route::post('/verify-otp-phone', 'VerifyMobileController@verifyOtpCode')->name('verifyOtpCode');
  Route::post('/verify-otp-phone/account', 'VerifyMobileController@verifyOtpCode')->name('verifyOtpCode.account');
  Route::get('/remove-session', 'VerifyMobileController@removeSession')->name('removeSession');
});

Route::group(
  ['namespace' => 'Front', 'as' => 'front.'],
  function () {
    Route::get('/', ['uses' => 'FrontController@index'])->name('index');
    Route::resource('rooms', 'RoomsController');
    Route::resource('booker', 'BookerController');

    Route::group(['middleware' => 'cookieRedirect'], function () {
      Route::get('/booking', ['uses' => 'FrontController@bookingPage'])->name('bookingPage');
      Route::get('/checkout', ['uses' => 'FrontController@checkoutPage'])->name('checkoutPage');
    });
    Route::get('/cart', ['uses' => 'FrontController@cartPage'])->name('cartPage');
    Route::get('/apply-coupon', ['uses' => 'FrontController@applyCoupon'])->name('apply-coupon');
    Route::get('/update-coupon', ['uses' => 'FrontController@updateCoupon'])->name('update-coupon');
    Route::get('/remove-coupon', ['uses' => 'FrontController@removeCoupon'])->name('remove-coupon');
    Route::get('/search', ['uses' => 'FrontController@searchServices'])->name('searchServices');
    Route::post('/add-or-update-product', ['uses' => 'FrontController@addOrUpdateProduct'])->name('addOrUpdateProduct');
    Route::post('/add-booking-details', ['uses' => 'FrontController@addBookingDetails'])->name('addBookingDetails');
    Route::post('/delete-product/{id}', ['uses' => 'FrontController@deleteProduct'])->name('deleteProduct');
    Route::post('/delete-front-product/{id}', ['uses' => 'FrontController@deleteProduct'])->name('deleteFrontProduct');
    Route::post('/update-cart', ['uses' => 'FrontController@updateCart'])->name('updateCart');
    Route::post('/check-user-availability', ['uses' => 'FrontController@checkUserAvailability'])->name('checkUserAvailability');
    Route::post('/grabDeal', ['uses' => 'FrontController@grabDeal'])->name('grabDeal');

    Route::post('/save-booking', ['uses' => 'FrontController@saveBooking'])->name('saveBooking');
    Route::group(['middleware' => 'mobileVerifyRedirect'], function () {
      Route::get('payment-gateway', array('as' => 'payment-gateway', 'uses' => 'FrontController@paymentGateway',));
      Route::get('offline-payment/{bookingId?}', array('as' => 'offline-payment', 'uses' => 'FrontController@offlinePayment',));
      Route::get('/payment-success/{paymentID?}', ['uses' => 'FrontController@paymentSuccess'])->name('payment.success');
      Route::get('/payment-fail/{paymentID?}', ['uses' => 'FrontController@paymentFail'])->name('payment.fail');
    });
    Route::post('/booking-slots', ['uses' => 'FrontController@bookingSlots'])->name('bookingSlots');
    Route::post('contact', ['uses' => 'FrontController@contact'])->name('contact');

    Route::get('paypal-recurring', array('as' => 'paypal-recurring', 'uses' => 'PaypalController@payWithPaypalRecurrring',));

    // route for view/blade file
    Route::get('paywithpaypal', array('as' => 'paywithpaypal', 'uses' => 'PaypalController@payWithPaypal',));
    // route for post request
    Route::get('paypal/{bookingId?}', array('as' => 'paypal', 'uses' => 'PaypalController@paymentWithpaypal',));
    // route for check status responce
    Route::get('paypal-status/{status?}', array('as' => 'status', 'uses' => 'PaypalController@getPaymentStatus',));

    Route::post('stripe/{bookingId?}', array('as' => 'stripe', 'uses' => 'StripeController@paymentWithStripe',));

    Route::post('razorpay', 'RazorPayController@paymentWithRazorpay')->name('razorpay');

    Route::post('change-language/{code}', 'FrontController@changeLanguage')->name('changeLanguage');

    Route::get('/{categorySlug}/{serviceSlug}', ['uses' => 'FrontController@serviceDetail'])->name('serviceDetail');

    Route::get('/deal/{dealId}/{dealSlug}', ['uses' => 'FrontController@dealDetail'])->name('dealDetail');

    Route::get('/aboutus', ['uses' => 'FrontController@aboutus'])->name('aboutus');

    Route::get('/gallery', ['uses' => 'FrontController@gallery'])->name('gallery');

    Route::get('/contactus', ['uses' => 'FrontController@contactus'])->name('contactus');

    Route::get('/ourservices', ['uses' => 'FrontController@ourservices'])->name('ourservices');

app/EmployeeGroup.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EmployeeGroup extends Model
{
    //------------------------------------ Attributes ---------------------------
    protected $guarded = ['id'];
    protected $table = 'employee_groups';


    //------------------------------------ Relations ----------------------------

    public function services() {
        return $this->hasMany(EmployeeGroupService::class, 'employee_groups_id', 'id', 'employee_group_services');
    }

} /* end of class */

app/Http/Controllers/Admin/EmployeeGroupController.php
<?php

namespace App\Http\Controllers\Admin;

use App\BusinessService;
use App\EmployeeGroup;
use App\Helper\Reply;
use App\Http\Requests\EmployeeGroup\StoreRequest;
use App\Http\Requests\EmployeeGroup\UpdateRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use EmployeeGroupsServices;
use Illuminate\Support\Facades\DB;

class EmployeeGroupController extends Controller
{

    public function __construct()
    {
        parent::__construct();
        view()->share('pageTitle', __('app.employeeGroup'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Exception
     */
    public function index()
    {
        abort_if(!$this->user->roles()->withoutGlobalScopes()->first()->hasPermission('read_employee_group'), 403);

        if(\request()->ajax()){
            $employeeGroup = EmployeeGroup::with('services')->get();
            // dd($employeeGroup);

            return \datatables()->of($employeeGroup)
                ->addColumn('action', function ($row) {
                    $action = '';

                    if ($this->user->roles()->withoutGlobalScopes()->first()->hasPermission('update_employee_group')) {
                        $action.= '<a href="' . route('admin.employee-group.edit', [$row->id]) . '" class="btn btn-primary btn-circle"
                          data-toggle="tooltip" data-original-title="'.__('app.edit').'"><i class="fa fa-pencil" aria-hidden="true"></i></a>';
                    }

                    if ($this->user->roles()->withoutGlobalScopes()->first()->hasPermission('delete_employee_group')) {
                        $action.= ' <a href="javascript:;" class="btn btn-danger btn-circle delete-row"
                          data-toggle="tooltip" data-row-id="' . $row->id . '" data-original-title="'.__('app.delete').'"><i class="fa fa-times" aria-hidden="true"></i></a>';
                    }

                    return $action;
                })
                ->editColumn('name', function ($row) {
                    return ucfirst($row->name);
                })
                ->editColumn('services', function ($row) {
                    $service_list = '';
                    foreach ($row->services as $key => $service) {
                        $service_list .= '<span style="margin:0.3em; padding:0.3em" class="badge badge-primary">'.$service->service->name.'</span>';
                    }
                    return $service_list=='' ? '--' : $service_list;
                })
                ->addIndexColumn()
                ->rawColumns(['action', 'services'])
                ->toJson();
        }

        return view('admin.employee-group.index');
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        abort_if(!$this->user->roles()->withoutGlobalScopes()->first()->hasPermission('create_employee_group'), 403);

        $business_services = BusinessService::all();

        return view('admin.employee-group.create', compact('business_services'));
    }

    /**
     * @param StoreRequest $request
     * @return array
     */
    public function store(StoreRequest $request)
    {
        abort_if(!$this->user->roles()->withoutGlobalScopes()->first()->hasPermission('create_employee_group'), 403);

        $user = new EmployeeGroup();
        $user->name = $request->name;
        $user->save();

        /* Assign services to users */
        $business_service_id = $request->business_service_id;
        if($business_service_id)
        {
            $assignedServices   = array();
            foreach ($business_service_id as $key => $service_id)
            {
                $assignedServices[$key]['business_service_id'] = $business_service_id[$key];
                $assignedServices[$key]['employee_groups_id'] = $user->id;
            }
            DB::table('employee_group_services')->insert($assignedServices);
        }


        return Reply::redirect(route('admin.employee-group.index'), __('messages.createdSuccessfully'));

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        abort_if(!$this->user->roles()->withoutGlobalScopes()->first()->hasPermission('update_employee_group'), 403);

        $employeeGroup = EmployeeGroup::where('id', $id)->first();


        /* push all previous assigned services to an array */
        $selectedServices = array();
        $assignedServices = EmployeeGroup::with(['services'])->find($id);
        foreach ($assignedServices->services as $key => $services)
        {
            array_push($selectedServices, $services->service->id);
        }
        $business_services = BusinessService::active()->get();

        return view('admin.employee-group.edit', compact('employeeGroup', 'selectedServices', 'business_services'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, $id)
    {
        abort_if(!$this->user->roles()->withoutGlobalScopes()->first()->hasPermission('update_employee_group'), 403);

        $user = EmployeeGroup::findOrFail($id);
        $user->name = $request->name;
        $user->save();

        /* Assign services to group */
        DB::table('employee_group_services')->where('employee_groups_id', $id)->delete();
        $business_service_id = $request->business_service_id;
        if($business_service_id)
        {
            $assignedServices   = array();
            foreach ($business_service_id as $key => $service_id)
            {
                $assignedServices[$key]['business_service_id'] = $business_service_id[$key];
                $assignedServices[$key]['employee_groups_id'] = $user->id;
            }
            DB::table('employee_group_services')->insert($assignedServices);
        }

        return Reply::redirect(route('admin.employee-group.index'), __('messages.updatedSuccessfully'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        abort_if(!$this->user->roles()->withoutGlobalScopes()->first()->hasPermission('delete_employee_group'), 403);

        EmployeeGroup::destroy($id);
        return Reply::success(__('messages.recordDeleted'));
    }
}

resources/views/admin/employee-group/create.blade.php
@extends('layouts.master')

@section('content')
<style>
    .select2-container--default.select2-container--focus .select2-selection--multiple {
        border-color: #999;
    }
    .select2-dropdown .select2-search__field:focus, .select2-search--inline .select2-search__field:focus {
        border: 0px;
    }
    .select2-container--default .select2-selection--multiple .select2-selection__rendered {
        margin: 0 13px;
    }
    .select2-container--default .select2-selection--multiple {
        border: 1px solid #cfd1da;
    }
    .select2-container--default .select2-selection--multiple .select2-selection__clear {
        cursor: pointer;
        float: right;
        font-weight: bold;
        margin-top: 8px;
        margin-right: 15px;
    }
</style>
    <div class="row">
        <div class="col-md-12">
            <div class="card card-dark">
                <div class="card-header">
                    <h3 class="card-title">@lang('app.add') @lang('app.employeeGroup')</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <form role="form" id="createForm"  class="ajax-form" method="POST">
                        @csrf

                        <div class="row">
                            <div class="col-md-12">
                                <!-- text input -->
                                <div class="form-group">
                                    <label>@lang('app.name')</label>
                                    <input type="text" class="form-control form-control-lg" name="name" value="">
                                </div>

                                <div class="form-group">
                                    <label>@lang('app.assignServices')</label>
                                    <select name="business_service_id[]" id="business_service_id" class="form-control form-control-lg select2" multiple="multiple" style="width: 100%">
                                        <option value="0">@lang('app.selectServices')</option>
                                        @foreach($business_services as $business_service)
                                            <option value="{{ $business_service->id }}">{{ $business_service->name }} ( {{ $business_service->location->name }} ) </option>
                                        @endforeach
                                    </select>
                                </div>

                                <div class="form-group">
                                    <button type="button" id="save-form" class="btn btn-success btn-light-round"><i
                                                class="fa fa-check"></i> @lang('app.save')</button>
                                </div>

                            </div>
                        </div>

                    </form>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
    </div>
@endsection

@push('footer-js')

    <script>

        $('#save-form').click(function () {

            $.easyAjax({
                url: '{{route('admin.employee-group.store')}}',
                container: '#createForm',
                type: "POST",
                redirect: true,
                file:true,
                data: $('#createForm').serialize()
            })
        });

    </script>

@endpush

resources/views/admin/employee-group/edit.blade.php
@extends('layouts.master')

@section('content')
<style>
    .select2-container--default.select2-container--focus .select2-selection--multiple {
        border-color: #999;
    }
    .select2-dropdown .select2-search__field:focus, .select2-search--inline .select2-search__field:focus {
        border: 0px;
    }
    .select2-container--default .select2-selection--multiple .select2-selection__rendered {
        margin: 0 13px;
    }
    .select2-container--default .select2-selection--multiple {
        border: 1px solid #cfd1da;
    }
    .select2-container--default .select2-selection--multiple .select2-selection__clear {
        cursor: pointer;
        float: right;
        font-weight: bold;
        margin-top: 8px;
        margin-right: 15px;
    }
</style>
    <div class="row">
        <div class="col-md-12">
            <div class="card card-dark">
                <div class="card-header">
                    <h3 class="card-title">@lang('app.edit') @lang('menu.employee')</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <form role="form" id="createForm"  class="ajax-form" method="POST">
                        @csrf
                        <div class="row">
                            <div class="col-md-12">
                                <!-- text input -->
                                <div class="form-group">
                                    <label>@lang('app.name')</label>
                                    <input type="text" class="form-control form-control-lg" name="name" value="{{ ucwords($employeeGroup->name) }}">
                                </div>

                                <div class="form-group">
                                    <label>@lang('app.assignServices')</label>
                                    <select name="business_service_id[]" id="business_service_id" class="form-control form-control-lg select2" multiple="multiple" style="width: 100%">
                                        <option value="0">@lang('app.selectServices')</option>
                                        @foreach($business_services as $business_service)
                                            <option @if(in_array($business_service->id, $selectedServices)) selected @endif value="{{ $business_service->id }}">{{ $business_service->name }} ( {{ $business_service->location->name }} ) </option>
                                        @endforeach
                                    </select>
                                </div>

                                <div class="form-group">
                                    <button type="button" id="save-form" class="btn btn-success btn-light-round"><i
                                                class="fa fa-check"></i> @lang('app.save')</button>
                                </div>
                            </div>
                        </div>

                    </form>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
    </div>
@endsection

@push('footer-js')

    <script>
        $('#save-form').click(function () {

            $.easyAjax({
                url: '{{route('admin.employee-group.update', $employeeGroup->id)}}',
                container: '#createForm',
                type: "PUT",
                redirect: true,
                data: $('#createForm').serialize()
            })
        });

    </script>

@endpush

resources/views/admin/employee-group/index.blade.php
@extends('layouts.master')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    @permission('create_employee_group')
                    <div class="d-flex justify-content-center justify-content-md-end mb-3">
                        <a href="{{ route('admin.employee-group.create') }}" class="btn btn-rounded btn-primary mb-1"><i class="fa fa-plus"></i> @lang('app.createNew')</a>
                    </div>
                    @endpermission
                    <div class="table-responsive">
                        <table id="myTable" class="table w-100">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>@lang('app.name')</th>
                                    <th>@lang('app.assign') @lang('app.service')</th>
                                    <th>@lang('app.action')</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('footer-js')
    <script>
        $(document).ready(function() {
            var table = $('#myTable').dataTable({
                responsive: true,
                processing: true,
                serverSide: true,
                ajax: '{!! route('admin.employee-group.index') !!}',
                language: languageOptions(),
                "fnDrawCallback": function( oSettings ) {
                    $("body").tooltip({
                        selector: '[data-toggle="tooltip"]'
                    });
                },
                columns: [
                    { data: 'DT_RowIndex'},
                    { data: 'name', name: 'name' },
                    { data: 'services', name: 'services' },
                    { data: 'action', name: 'action', width: '20%' }
                ]
            });
            new $.fn.dataTable.FixedHeader( table );

            $('body').on('click', '.delete-row', function(){
                var id = $(this).data('row-id');
                swal({
                    icon: "warning",
                    buttons: ["@lang('app.cancel')", "@lang('app.ok')"],
                    dangerMode: true,
                    title: "@lang('errors.areYouSure')",
                    text: "@lang('errors.deleteWarning')",
                })
                    .then((willDelete) => {
                        if (willDelete) {
                            var url = "{{ route('admin.employee-group.destroy',':id') }}";
                            url = url.replace(':id', id);

                            var token = "{{ csrf_token() }}";

                            $.easyAjax({
                                type: 'POST',
                                url: url,
                                data: {'_token': token, '_method': 'DELETE'},
                                success: function (response) {
                                    if (response.status == "success") {
                                        $.unblockUI();
//                                    swal("Deleted!", response.message, "success");
                                        table._fnDraw();
                                    }
                                }
                            });
                        }
                    });
            });
        } );
    </script>
@endpush