routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

// Admin routes
Route::group(['middleware' => 'auth'], function () {

  // Route::post('mark-notification-read', ['uses' => 'NotificationController@markAllRead'])->name('mark-notification-read');

  // Admin routes
  Route::group(
    ['namespace' => 'Admin', 'prefix' => 'account', 'as' => 'admin.'],
    function () {

      Route::post('business-services/store-images', 'BusinessServiceController@storeImages')->name('business-services.storeImages');
      Route::post('business-services/update-images', 'BusinessServiceController@updateImages')->name('business-services.updateImages');

      Route::get('coupons/data', 'CouponController@data')->name('coupons.data');

      Route::post('todo-items/update-todo-item', 'TodoItemController@updateTodoItem')->name('todo-items.updateTodoItem');

      Route::post('save-booking-times-field', 'SettingController@saveBookingTimesField')->name('save-booking-times-field');

      Route::resources(
        [
          'locations' => 'LocationController',
          'categories' => 'CategoryController',
          'business-services' => 'BusinessServiceController',
          'pages' => 'PageController',
          'settings' => 'SettingController',
          'booking-times' => 'BookingTimeController',
          'tax-settings' => 'TaxSettingController',
          'currency-settings' => 'CurrencySettingController',
          'language-settings' => 'LanguageSettingController',
          'email-settings' => 'SmtpSettingController',
          'theme-settings' => 'ThemeSettingController',
          'front-theme-settings' => 'FrontThemeSettingController',
          'customers' => 'CustomerController',
          'credential' => 'PaymentCredentialSettingController',
          'sms-settings' => 'SmsSettingController',
          'coupons' => 'CouponController',
          'sms-settings' => 'SmsSettingController',
          'todo-items' => 'TodoItemController',
          'deals' => 'DealController',
        ]
      );


      Route::post('selectLocation', 'DealController@selectLocation')->name('deals.selectLocation');
      Route::post('selectServices', 'DealController@selectServices')->name('deals.selectServices');
      Route::get('resetSelection', 'DealController@resetSelection')->name('deals.resetSelection');
      Route::post('makeDealWithMultipleLocation', 'DealController@makeDealWithMultipleLocation')->name('deals.makeDealWithMultipleLocation');
      Route::post('makeDeal', 'DealController@makeDeal')->name('deals.makeDeal');
      Route::post('makeDealMultipleLocation', 'DealController@makeDealMultipleLocation')->name('deals.makeDealMultipleLocation');


      Route::post('change-language/{code}', 'SettingController@changeLanguage')->name('changeLanguage');

      Route::post('change-language/{code}', 'SettingController@changeLanguage')->name('changeLanguage');
      Route::post('role-permission/add-role', 'RolePermissionSettingController@addRole')->name('role-permission.addRole');
      Route::post('role-permission/add-members/{role_id}', 'RolePermissionSettingController@addMembers')->name('role-permission.addMembers');
      Route::get('role-permission/get-members/{role_id}', 'RolePermissionSettingController@getMembers')->name('role-permission.getMembers');
      Route::get('role-permission/get-members-to-add/{id}', 'RolePermissionSettingController@getMembersToAdd')->name('role-permission.getMembersToAdd');
      Route::delete('role-permission/remove-member', 'RolePermissionSettingController@removeMember')->name('role-permission.removeMember');
      Route::get('role-permission/data', 'RolePermissionSettingController@data')->name('role-permission.data');
      Route::post('role-permission/toggleAllPermissions', 'RolePermissionSettingController@toggleAllPermissions')->name('role-permission.toggleAllPermissions');
      Route::resource('role-permission', 'RolePermissionSettingController');

      Route::put('change-language-status/{id}', 'LanguageSettingController@changeStatus')->name('language-settings.changeStatus');
      Route::get('smtp-settings/sent-test-email', ['uses' => 'SmtpSettingController@sendTestEmail'])->name('email-settings.sendTestEmail');
      Route::get('reports/earningTable', ['uses' => 'ReportController@earningTable'])->name('reports.earningTable');
      Route::post('reports/earningChart', ['uses' => 'ReportController@earningReportChart'])->name('reports.earningReportChart');
      Route::get('reports', ['uses' => 'ReportController@index'])->name('reports.index');

      Route::get('reports/salesTable', ['uses' => 'ReportController@salesTable'])->name('reports.salesTable');
      Route::get('reports/tabularTable', ['uses' => 'ReportController@tabularTable'])->name('reports.tabularTable');
      Route::post('reports/salesChart', ['uses' => 'ReportController@salesReportChart'])->name('reports.salesReportChart');

      /* Graphical reporting section  */
      Route::get('reports/userTypeChart', ['uses' => 'ReportController@userTypeChart'])->name('reports.userTypeChart');
      Route::get('reports/serviceTypeChart', ['uses' => 'ReportController@serviceTypeChart'])->name('reports.serviceTypeChart');
      Route::get('reports/bookingSourceChart', ['uses' => 'ReportController@bookingSourceChart'])->name('reports.bookingSourceChart');
      Route::post('reports/bookingPerDayChart', ['uses' => 'ReportController@bookingPerDayChart'])->name('reports.bookingPerDayChart');
      Route::post('reports/paymentPerDayChart', ['uses' => 'ReportController@paymentPerDayChart'])->name('reports.paymentPerDayChart');
      Route::post('reports/bookingPerMonthChart', ['uses' => 'ReportController@bookingPerMonthChart'])->name('reports.bookingPerMonthChart');
      Route::post('reports/paymentPerMonthChart', ['uses' => 'ReportController@paymentPerMonthChart'])->name('reports.paymentPerMonthChart');
      Route::post('reports/bookingPerYearChart', ['uses' => 'ReportController@bookingPerYearChart'])->name('reports.bookingPerYearChart');
      Route::post('reports/bookingPerYearChart', ['uses' => 'ReportController@bookingPerYearChart'])->name('reports.bookingPerYearChart');
      Route::post('reports/paymentPerYearChart', ['uses' => 'ReportController@paymentPerYearChart'])->name('reports.paymentPerYearChart');

      Route::get('reports/customer', ['uses' => 'ReportController@customer'])->name('reports.customer');
      Route::get('pos/select-customer', ['uses' => 'POSController@selectCustomer'])->name('pos.select-customer');
      Route::get('pos/search-customer', ['uses' => 'POSController@searchCustomer'])->name('pos.search-customer');
      Route::get('pos/filter-services', ['uses' => 'POSController@filterServices'])->name('pos.filter-services');
      Route::get('pos/addCart', ['uses' => 'POSController@addCart'])->name('pos.addCart');
      Route::post('pos/apply-coupon', ['uses' => 'POSController@applyCoupon'])->name('pos.apply-coupon');
      Route::post('pos/update-coupon', ['uses' => 'POSController@updateCoupon'])->name('pos.update-coupon');
      Route::resource('pos', 'POSController');

      Route::post('employee/changeRole', 'EmployeeController@changeRole')->name('employee.changeRole');
      Route::resource('employee', 'EmployeeController');
      Route::resource('employee-group', 'EmployeeGroupController');

      Route::resource('update-application', 'UpdateApplicationController');
      Route::resource('search', 'SearchController');

      Route::get('dashboard', 'ShowDashboard')->name('dashboard');

      Route::post('bookings/update-coupon', ['uses' => 'BookingController@updateCoupon'])->name('bookings.update-coupon');
      Route::post('multiStatusUpdate', ['uses' => 'BookingController@multiStatusUpdate'])->name('bookings.multiStatusUpdate');
      Route::post('sendReminder', ['uses' => 'BookingController@sendReminder'])->name('bookings.sendReminder');
      Route::post('bookings/{status?}', ['uses' => 'BookingController@index'])->name('bookings.index');
      Route::post('bookings/requestCancel/{id}', ['uses' => 'BookingController@requestCancel'])->name('bookings.requestCancel');
      Route::get('bookings/download/{id}', ['uses' => 'BookingController@download'])->name('bookings.download');
      Route::resources([
        'bookings' => 'BookingController',
        'profile' => 'ProfileController'
      ]);
    }
  );

  Route::get('change-mobile', 'VerifyMobileController@changeMobile')->name('changeMobile');
  Route::post('/send-otp-code', 'VerifyMobileController@sendVerificationCode')->name('sendOtpCode');
  Route::post('/send-otp-code/account', 'VerifyMobileController@sendVerificationCode')->name('sendOtpCode.account');
  Route::post('/verify-otp-phone', 'VerifyMobileController@verifyOtpCode')->name('verifyOtpCode');
  Route::post('/verify-otp-phone/account', 'VerifyMobileController@verifyOtpCode')->name('verifyOtpCode.account');
  Route::get('/remove-session', 'VerifyMobileController@removeSession')->name('removeSession');
});

Route::group(
  ['namespace' => 'Front', 'as' => 'front.'],
  function () {
    Route::get('/', ['uses' => 'FrontController@index'])->name('index');
    Route::resource('rooms', 'RoomsController');
    Route::resource('booker', 'BookerController');

    Route::group(['middleware' => 'cookieRedirect'], function () {
      Route::get('/booking', ['uses' => 'FrontController@bookingPage'])->name('bookingPage');
      Route::get('/checkout', ['uses' => 'FrontController@checkoutPage'])->name('checkoutPage');
    });
    Route::get('/cart', ['uses' => 'FrontController@cartPage'])->name('cartPage');

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Laratrust\Models\LaratrustRole;

class Role extends LaratrustRole
{

    //------------------------------------ Attributes ---------------------------

    protected $guarded = [];

    protected static function boot() {
        parent::boot();
        static::addGlobalScope('withoutCustomerRole', function (Builder $builder) {
            $builder->where('name', '<>', 'customer');
        });
    }

    //------------------------------------ Relations ----------------------------

    public function getRoleCount() {
        return $this->hasMany(User::class);
    }

    //------------------------------------ Accessors ----------------------------

    public function getMemberCountAttribute() {
        return $this->users->count();
    }

} /* end of class */

resources/views/admin/role-permission/create.blade.php
<div class="modal-header">
    <h4 class="modal-title">@lang('modules.rolePermission.manageRole')</h4>
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
</div>
<div class="modal-body">
    <div class="table-responsive">
        <table id="roleTable" class="table w-100">
            <thead>
                <tr>
                    <th>#</th>
                    <th>@lang('modules.rolePermission.tables.roleName')</th>
                    <th>@lang('modules.rolePermission.tables.roleDescription')</th>
                    <th>@lang('app.action')</th>
                </tr>
            </thead>
        </table>
    </div>

    <hr>
    <div id="create-edit-form">
        @include('admin.role-permission.create_form')
    </div>
</div>

<script>
    roleTable = $('#roleTable').dataTable({
        destroy: true,
        responsive: true,
        processing: true,
        serverSide: true,
        pageLength: 3,
        lengthChange: false,
        ajax: '{!! route('admin.role-permission.data') !!}',
        language: languageOptions(),
        "fnDrawCallback": function( oSettings ) {
            $("body").tooltip({
                selector: '[data-toggle="tooltip"]'
            });
        },
        order: [[1, 'ASC']],
        columns: [
            { data: 'DT_RowIndex', searchable: false, orderable: false },
            { data: 'display_name', name: 'display_name' },
            { data: 'description', name: 'description' },
            { data: 'action', name: 'action', width: '20%' }
        ]
    });
</script>

resources/views/admin/role-permission/create_form.blade.php
<form id="create-role" class="ajax-form">
    @csrf
    <div class="form-body">
        <h5>@lang('modules.rolePermission.addRole')</h5>
        <div class="row">
            <div class="col-sm-12 ">
                <div class="form-group">
                    <label>@lang('modules.rolePermission.forms.displayName')</label>
                    <input type="text" name="display_name" id="display_name" class="form-control">
                </div>
            </div>
            <div class="col-sm-12 ">
                <div class="form-group">
                    <label>@lang('modules.rolePermission.forms.description')</label>
                    <input type="text" name="description" id="description" class="form-control">
                </div>
            </div>
        </div>
    </div>
    <div class="form-actions">
        <button type="button" id="save-create-role" class="btn btn-success"> <i class="fa fa-check"></i>
            @lang('app.add')</button>
    </div>
</form>

resources/views/admin/role-permission/edit_form.blade.php
<form id="edit-role" data-role-id="{{ $role->id }}" class="ajax-form">
    @csrf
    @method('PUT')
    <div class="form-body">
        <h5>@lang('modules.rolePermission.editRole')</h5>
        <div class="row">
            <div class="col-sm-12 ">
                <div class="form-group">
                    <label>@lang('modules.rolePermission.forms.displayName')</label>
                    <input type="text" name="display_name" id="display_name" class="form-control" value="{{ $role->display_name }}">
                </div>
            </div>
            <div class="col-sm-12 ">
                <div class="form-group">
                    <label>@lang('modules.rolePermission.forms.description')</label>
                    <input type="text" name="description" id="description" class="form-control" value="{{ $role->description }}">
                </div>
            </div>
        </div>
    </div>
    <div class="form-actions">
        <button type="button" id="save-edit-role" class="btn btn-success"> <i class="fa fa-check"></i>
            @lang('app.update')</button>
        <button type="button" id="cancel-edit-role" class="btn btn-default"> <i class="fa fa-close"></i>
            @lang('app.cancel')</button>
    </div>
</form>

resources/views/admin/role-permission/index.blade.php
<h4>@lang('menu.rolesPermissions')</h4>
<div class="col-sm-12">
    <a href="javascript:;" id="addRole" class="btn btn-success btn-sm btn-outline waves-effect waves-light "><i class="fa fa-gear"></i> @lang("modules.rolePermission.addRole")</a>
</div>

@foreach($roles as $role)
    <div class="col-md-12 b-all mt-2">
        <div class="row bg-dark p-3 justify-content-center align-items-center">
            <div class="col-md-4">
                <h5 class="text-white mt-2 mb-2"><strong>{{ ucwords($role->display_name) }}</strong></h5>
            </div>
            <div class="col-md-4 text-center role-members">
                <button class="btn btn-xs btn-danger btn-rounded show-members" data-role-id="{{ $role->id }}"><i class="fa fa-users"></i> {{ $role->member_count  }} @lang('modules.rolePermission.members')</button>
            </div>
            <div class="col-md-4">
                <button class="btn btn-default btn-sm btn-rounded pull-right" onclick="toggle('#role-permission-{{ $role->id }}')" data-role-id="{{ $role->id }}"><i class="fa fa-key"></i> @lang('modules.rolePermission.permissions')</button>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 b-t permission-section" style="display: none;" id="role-permission-{{ $role->id }}" >
                <table class="table ">
                    <thead>
                    <tr class="bg-white">
                        <th>
                            <div class="form-group d-flex">
                                <label class="switch mr-2">
                                    <input type="checkbox"
                                        @if(count($role->permissions) == $totalPermissions)
                                            checked
                                        @endif onchange="toggleAllPermissions({ roleId: {{ $role->id }}}, this);">
                                    <span class="slider round"></span>
                                </label>
                                @lang('modules.rolePermission.selectAll')
                            </div>
                        </th>
                        <th>@lang('app.add')</th>
                        <th>@lang('app.view')</th>
                        <th>@lang('app.update')</th>
                        <th>@lang('app.delete')</th>
                    </tr>
                    </thead>
                    <tbody>
                        @foreach($modules as $module)
                            <tr>
                                <td>{{ __('app.'.\Illuminate\Support\Str::camel($module->display_name)) }}

                                    @if($module->description != trans($module->description))
                                        <a class="mytooltip" data-toggle="tooltip" data-placement="top" title="@lang($module->description)">
                                            <i class="fa fa-info-circle"></i>
                                        </a>
                                    @endif
                                </td>

                                @foreach($module->permissions as $permission)
                                    <td>
                                        <label class="switch permissions">
                                            <input type="checkbox"
                                                @if($role->hasPermission([$permission->name]))
                                                    checked
                                                @endif value="active" onchange="togglePermission({ roleId: {{ $role->id }}, permissionId: {{ $permission->id }}}, this);">
                                            <span class="slider round"></span>
                                        </label>
                                    </td>
                                @endforeach

                                @if(count($module->permissions) < 4)
                                    @for($i=1; $i<=(4-count($module->permissions)); $i++)
                                        <td>&nbsp;</td>
                                    @endfor
                                @endif

                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endforeach

@push('footer-js')
    <script>
        const create_form = `@include('admin.role-permission.create_form')`;
        let table_modified = false;

        function togglePermission(options, ele) {
            let assignPermission = 'no';

            if ($(ele).is(':checked')) {
                assignPermission = 'yes';
            }

            options = {...options, _token: '{{ csrf_token() }}', assignPermission};

            $.easyAjax({
                url: '{{ route('admin.role-permission.store') }}',
                type: 'POST',
                data: options,
            })
        }

        function toggleAllPermissions(options, ele) {
            let assignPermission = 'no';

            if ($(ele).is(':checked')) {
                assignPermission = 'yes';
            }

            options = {...options, _token: '{{ csrf_token() }}', assignPermission};

            $.easyAjax({
                url: '{{ route('admin.role-permission.toggleAllPermissions') }}',
                type: 'POST',
                data: options,
                success: function (response) {
                    if (response.status == 'success') {
                        $(`#role-permission-${ options.roleId } .permissions input`).each(function (index, input) {
                            if ($(ele).is(':checked') !== $(input).is(':checked')) {
                                $(input).prop('checked', $(ele).is(':checked'));
                            }
                        })
                    }
                }
            })
        }

        $('#addRole').click(function () {
            const url = '{{ route('admin.role-permission.create') }}';

            $.ajaxModal('#application-lg-modal', url);
        })

        $('#application-lg-modal').on('hide.bs.modal', function (e) {
            if (table_modified) {
                window.location.reload();
            }
            else {
                $('#roleTable').DataTable().destroy();
            }
        })

        $('body').on('click', '#save-create-role', function () {
            var url = '{{ route("admin.role-permission.addRole")}}';

            $.easyAjax({
                url: url,
                type: 'POST',
                data: $('#create-role').serialize(),
                container: '#application-lg-modal',
                success: function (response) {
                    $('#create-edit-form').html(create_form);
                    roleTable.fnDraw();
                    table_modified = true;
                }
            })
        })

        $('body').on('click', '.edit-role', function () {
            var id = $(this).data('role-id');
            var url = '{{ route("admin.role-permission.edit", ":id")}}';
            url = url.replace(':id', id);

            $.easyAjax({
                url: url,
                type: 'GET',
                container: '#application-lg-modal',
                success: function (response) {
                    $('#create-edit-form').html(response.view);
                }
            })
        })

        $('body').on('click', '#save-edit-role', function () {
            const id = $('#edit-role').data('role-id');
            var url = '{{ route("admin.role-permission.update", ":id")}}';
            url = url.replace(':id', id);

            $.easyAjax({
                url: url,
                type: 'PUT',
                data: $('#edit-role').serialize(),
                container: '#application-lg-modal',
                success: function (response) {
                    $('#create-edit-form').html(create_form);
                    roleTable.fnDraw();
                    table_modified = true;
                }
            })
        })

        $('body').on('click', '#cancel-edit-role', function () {
            $('#create-edit-form').html(create_form);
        })

        $('body').on('click', '.delete-role', function () {
            const id = $(this).data('role-id');
            swal({
                icon: "warning",
                buttons: ["@lang('app.cancel')", "@lang('app.ok')"],
                dangerMode: true,
                title: "@lang('errors.areYouSure')",
                text: "@lang('errors.deleteWarning')",
            })
            .then((willDelete) => {
                if (willDelete) {
                    var url = '{{ route("admin.role-permission.destroy", ":id")}}';
                    url = url.replace(':id', id);
                    const _token = '{{ csrf_token() }}';

                    $.easyAjax({
                        url: url,
                        type: 'POST',
                        data: { _token, _method: 'DELETE' },
                        container: '#application-lg-modal',
                        success: function (response) {
                            roleTable.fnDraw();
                            table_modified = true;
                        }
                    });
                }
            });
        })

        $('.show-members').click(function () {
            const id = $(this).data('role-id');
            let url = '{{ route('admin.role-permission.show', ':id') }}';
            url = url.replace(':id', id);

            $.ajaxModal('#application-lg-modal', url);
        })
    </script>
@endpush

resources/views/admin/role-permission/show.blade.php
<div class="modal-header">
    <h4 class="modal-title">@lang('modules.rolePermission.manageMembers')</h4>
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
</div>
<div class="modal-body">
    <div class="table-responsive">
        <table id="roleMemberTable" class="table w-100">
            <thead>
                <tr>
                    <th>#</th>
                    <th>@lang('modules.rolePermission.tables.memberName')</th>
                    <th>@lang('modules.rolePermission.tables.memberRole')</th>
                    <th>@lang('app.action')</th>
                </tr>
            </thead>
        </table>
    </div>

    <hr>
    <form id="add-member-form" class="ajax-form">
        @csrf
        <div class="form-body">
            <h5>@lang('modules.rolePermission.addMember')</h5>
            <div class="row">
                <div class="col-sm-12 ">
                    <div class="form-group">
                        <label>@lang('modules.rolePermission.members')</label>
                        <select class="form-control select2 select2-multiple" name="user_ids[]" id="user_ids" multiple="multiple" data-placeholder="@lang('modules.rolePermission.forms.addMembers')">
                            @foreach ($usersToAdd as $member)
                                <option value="{{ $member->id }}">{{ $member->name }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-actions">
            <button type="button" id="save-add-member" class="btn btn-success"> <i class="fa fa-check"></i>
                @lang('app.add')</button>
        </div>
    </form>
</div>

<script>
    $('#user_ids').select2({
        allowClear: true
    });

    function renderSelect() {
        $.easyAjax({
            url: '{{ route('admin.role-permission.getMembersToAdd', $id) }}',
            type: 'GET',
            success: function (response) {
                let options = '';
                response.usersToAdd.forEach(user => {
                    options += `<option value='${user.id}'>${user.name}</option>`;
                })

                $('#user_ids').html(options);
                $('#user_ids').select2();
            }
        })
    }

    roleMemberTable = $('#roleMemberTable').dataTable({
        destroy: true,
        responsive: true,
        processing: true,
        serverSide: true,
        pageLength: 3,
        lengthChange: false,
        ajax: '{!! route('admin.role-permission.getMembers', ['role_id' => $id]) !!}',
        language: languageOptions(),
        "fnDrawCallback": function( oSettings ) {
            $("body").tooltip({
                selector: '[data-toggle="tooltip"]'
            });
        },
        order: [[1, 'ASC']],
        columns: [
            { data: 'DT_RowIndex', searchable: false, orderable: false },
            { data: 'name', name: 'name' },
            { data: 'roles.display_name', name: 'roles.display_name', sortable: false },
            { data: 'action', name: 'action', width: '20%' }
        ]
    });

    $('#save-add-member').click(function () {
        $.easyAjax({
            url: '{{ route('admin.role-permission.addMembers', ['role_id' => $id]) }}',
            type: 'POST',
            data: $('#add-member-form').serialize(),
            container: '#add-member-form',
            success: function (response) {
                if (response.status == 'success') {
                    roleMemberTable.fnDraw();
                    $('#user_ids').val(null).trigger('change');
                    table_modified = true;
                    renderSelect();
                }
            }
        })
    })

    $('body').on('click', '.delete-member', function () {
        const id = $(this).data('user-id');
        swal({
            icon: "warning",
            buttons: ["@lang('app.cancel')", "@lang('app.ok')"],
            dangerMode: true,
            title: "@lang('errors.areYouSure')",
            text: "@lang('errors.deleteWarning')",
        })
        .then((willDelete) => {
            if (willDelete) {
                let url = '{{ route('admin.role-permission.removeMember') }}';

                let data = {
                    _token: '{{ csrf_token() }}',
                    _method: 'DELETE',
                    user_id: id
                }

                $.easyAjax({
                    url,
                    data,
                    type: 'POST',
                    container: '#roleMemberTable',
                    success: function (response) {
                        if (response.status == 'success') {
                            roleMemberTable.fnDraw();
                            table_modified = true;
                            $('#user_ids').val(null).trigger('change');
                            renderSelect();
                        }
                    }
                })
            }
        });
    })
</script>